workflows:
  ios_build:
    name: iOS App Build (Capacitor + Vite)
    max_build_duration: 120
    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.dashboard.app"
        SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
      node: "18.16.0"
      xcode: "16.1"
      cocoapods: default

    scripts:
      - name: Install NPM dependencies
        script: |
          npm ci

      - name: Build Web (Vite)
        script: |
          npm run build

      - name: Sync Capacitor iOS and install Pods
        script: |
          npx cap copy
          npx cap sync ios
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS archive (xcodebuild)
        script: |
          set -o pipefail
          mkdir -p build
          # Archive the app (adjust workspace and scheme if different)
          xcodebuild -workspace "${XCODE_WORKSPACE}" \
            -scheme "${SCHEME}" \
            -configuration Release \
            -archivePath build/App.xcarchive \
            clean archive | xcpretty || cat

      - name: Export .ipa from archive
        script: |
          # Ensure exportOptions.plist exists at ios/exportOptions.plist
          if [ ! -f ios/exportOptions.plist ]; then
            echo "Error: ios/exportOptions.plist not found. Create it as instructed." >&2
            exit 1
          fi
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa | xcpretty || cat

    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        testflight:
          notify_external_testers: true
