workflows:
  ios_build:
    name: iOS App Build (Capacitor + Vite)
    max_build_duration: 120
    environment:
      groups:
        - appstore_credentials   # you will create this group in Codemagic (explained below)
      vars:
        BUNDLE_ID: "com.dashboard.app"
        SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
      node: "18.16.0"
      xcode: "16.1"
      cocoapods: default

    scripts:
      - name: Install NPM dependencies
        script: |
          npm ci

      - name: Build Web (Vite)
        script: |
          npm run build

      - name: Sync Capacitor iOS and install Pods
        script: |
          npx cap copy
          npx cap sync ios
          cd ios
          pod install --repo-update
          cd ..

    artifacts:
      - build/ios/**/*.ipa
      - build/ios/**/*.xcarchive

    publishing:
      app_store_connect:
        # App Store Connect API authentication requires all three:
        # - api_key: the contents of the private key (.p8)
        # - key_id: the Key ID from App Store Connect
        # - issuer_id: the Issuer ID from App Store Connect
        api_key: $APP_STORE_CONNECT_API_KEY   # .p8 private key contents
        key_id: $APP_STORE_CONNECT_KEY_ID     # e.g. ABCDE12345
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # e.g. 12345678-1234-1234-1234-123456789012
        submit_to_testflight: true
