workflows:
  ios_build:
    name: iOS App Build (Capacitor + Vite)
    max_build_duration: 120
    environment:
      groups:
        - appstore_credentials   # you will create this group in Codemagic (explained below)
      vars:
        BUNDLE_ID: "com.dashboard.app"
        SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
      node: "18.16.0"
      xcode: "15.2"
      cocoapods: default

    scripts:
      - name: Install NPM dependencies
        script: |
          npm ci

      - name: Build Web (Vite)
        script: |
          npm run build

      - name: Sync Capacitor iOS and install Pods
        script: |
          npx cap copy
          npx cap sync ios
          cd ios
          pod install --repo-update
          cd ..

    artifacts:
      - build/ios/**/*.ipa
      - build/ios/**/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY   # stored as env variable
        submit_to_testflight: true
        testflight:
          notify_external_testers: true
